"""
Claude CLI integration for forge.

forge sync   — write compiled docs to CLAUDE.md (auto-loaded every session)
forge task   — run a one-shot task: context → system prompt, task → user message
forge chat   — open interactive claude session with forge context in system prompt
"""

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

import click
from rich.console import Console

console = Console()

# Markers so forge can update its section without clobbering user content
_FORGE_START = "<!-- forge:start -->"
_FORGE_END   = "<!-- forge:end -->"

_SESSION_FILE = ".forge/session.md"


# ── helpers ───────────────────────────────────────────────────────────────────

def _check_claude() -> None:
    if not shutil.which("claude"):
        console.print(
            "[red]claude CLI not found.[/red]\n"
            "Install it from: https://claude.ai/code"
        )
        raise SystemExit(1)


def _compile(compress: bool = True, with_context: bool = True,
             ext: tuple = (), max_files: int = 20) -> str:
    """Compile forge docs + optional codebase into a single string."""
    from forge.commands.run import _load_docs, _collect_context_files
    from forge.core.compress import compress as compress_fn

    doc_sections = _load_docs()
    if not doc_sections:
        return ""

    parts = []
    for _filename, title, content in doc_sections:
        c = compress_fn(content) if compress else content
        parts.append(f"## {title}\n\n{c}")

    if with_context:
        _skip_names = {"CLAUDE.md", "AGENTS.md"}
        ctx_files = [
            (f, c) for f, c in _collect_context_files(root=".", extensions=ext, max_files=max_files)
            if os.path.basename(f) not in _skip_names
            and not os.path.normpath(f).startswith(".forge")
        ]
        if ctx_files:
            blocks = []
            for f, content in ctx_files:
                if content.startswith("["):
                    blocks.append(f"**{f}**\n{content}")
                else:
                    c = compress_fn(content) if compress else content
                    blocks.append(f"**{f}**\n```\n{c}\n```")
            parts.append("## Codebase\n\n" + "\n\n".join(blocks))

    return "\n\n---\n\n".join(parts)


def _write_session_file(content: str) -> Path:
    """Write compiled context to .forge/session.md and return its path."""
    path = Path(_SESSION_FILE)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return path.resolve()


def _update_claude_md(content: str) -> tuple[Path, bool]:
    """
    Insert/replace the forge section in CLAUDE.md.
    Returns (path, created) where created=True if the file didn't exist before.
    """
    forge_block = (
        f"{_FORGE_START}\n"
        f"<!-- Auto-generated by forge — edit .forge/docs/ not this block -->\n\n"
        f"{content}\n\n"
        f"{_FORGE_END}"
    )
    claude_md = Path("CLAUDE.md")
    created = not claude_md.exists()

    if claude_md.exists():
        existing = claude_md.read_text()
        if _FORGE_START in existing:
            start = existing.find(_FORGE_START)
            end   = existing.find(_FORGE_END, start) + len(_FORGE_END)
            new   = existing[:start] + forge_block + existing[end:]
        else:
            new = forge_block + "\n\n" + existing
    else:
        new = forge_block + "\n"

    claude_md.write_text(new)
    return claude_md, created


# ── commands ──────────────────────────────────────────────────────────────────

@click.command("sync")
@click.option("--compress/--no-compress", default=True, show_default=True)
@click.option("--no-context", "skip_context", is_flag=True,
              help="Exclude codebase files")
@click.option("--dry-run", is_flag=True,
              help="Print what would be written without touching CLAUDE.md")
@click.option("--strip", is_flag=True,
              help="Remove the forge section from CLAUDE.md")
def sync(compress, skip_context, dry_run, strip):
    """
    Write forge docs to CLAUDE.md so Claude CLI picks them up automatically.

    \b
    Claude CLI reads CLAUDE.md at the start of every session.
    Run `forge sync` whenever your spec docs change.
    Your own content in CLAUDE.md is never touched — forge only manages
    the section between <!-- forge:start --> and <!-- forge:end -->.

    \b
    Examples:
      forge sync                 update CLAUDE.md with current docs
      forge sync --no-context    docs only, skip codebase files
      forge sync --dry-run       preview without writing
      forge sync --strip         remove forge section from CLAUDE.md
    """
    claude_md = Path("CLAUDE.md")

    if strip:
        if not claude_md.exists() or _FORGE_START not in claude_md.read_text():
            console.print("[dim]No forge section found in CLAUDE.md.[/dim]")
            return
        existing = claude_md.read_text()
        start = existing.find(_FORGE_START)
        end   = existing.find(_FORGE_END) + len(_FORGE_END)
        cleaned = (existing[:start] + existing[end:]).strip()
        if not dry_run:
            claude_md.write_text(cleaned + "\n" if cleaned else "")
            console.print("[green]✓[/green] Removed forge section from CLAUDE.md.")
        else:
            console.print("[dim]Would remove forge section from CLAUDE.md.[/dim]")
        return

    try:
        content = _compile(compress=compress, with_context=not skip_context)
    except FileNotFoundError:
        console.print("[red]Run `forge init` first.[/red]")
        return

    if not content:
        console.print(
            "[yellow]No docs found.[/yellow] Run [bold]forge docs scaffold[/bold] first."
        )
        return

    if dry_run:
        console.print(content)
        return

    _, created = _update_claude_md(content)
    from forge.core.compress import estimate_tokens
    tok = estimate_tokens(content)
    verb = "created" if created else "updated"
    console.print(
        f"[green]✓[/green] CLAUDE.md {verb}  "
        f"[dim](~{tok:,} tokens | compression {'on' if compress else 'off'})[/dim]"
    )
    console.print(
        "[dim]Claude CLI reads this automatically — just run `claude` to start.[/dim]"
    )


@click.command("task")
@click.argument("description")
@click.option("--compress/--no-compress", default=True, show_default=True)
@click.option("--no-context", "skip_context", is_flag=True,
              help="Docs only, skip codebase files")
@click.option("--ext", "-e", multiple=True,
              help="Only include these file extensions (e.g. -e .py)")
@click.option("--max-files", default=20, show_default=True)
@click.option("--model", "-m", default="", help="Claude model alias (e.g. sonnet, opus)")
@click.option("--output-format", "fmt",
              type=click.Choice(["text", "json", "stream-json"]),
              default="text", show_default=True)
def task(description, compress, skip_context, ext, max_files, model, fmt):
    """
    Run a one-shot task through Claude CLI with forge context injected.

    Forge compiles your spec docs (and optionally codebase) into the system
    prompt, then fires `claude -p "<description>"` so you get a direct answer
    without an interactive session.

    \b
    Examples:
      forge task "implement the login endpoint from TASK-1"
      forge task "write pytest tests for auth.py" -e .py
      forge task "what does models.py do?" --no-context
      forge task "refactor auth.py" --model opus
    """
    _check_claude()

    try:
        content = _compile(
            compress=compress,
            with_context=not skip_context,
            ext=tuple(ext),
            max_files=max_files,
        )
    except FileNotFoundError:
        console.print("[red]Run `forge init` first.[/red]")
        return

    from forge.core.compress import estimate_tokens

    if content:
        session_path = _write_session_file(content)
        tok = estimate_tokens(content)
        console.print(
            f"[dim]Context: ~{tok:,} tokens | "
            f"{len(content.splitlines())} lines → system prompt[/dim]\n"
        )
        cmd = ["claude", "-p", description,
               "--append-system-prompt-file", str(session_path)]
    else:
        console.print("[dim]No forge docs found — sending task without context.[/dim]\n")
        cmd = ["claude", "-p", description]

    if model:
        cmd += ["--model", model]
    if fmt != "text":
        cmd += ["--output-format", fmt]

    # Replace current process with claude — output streams directly to terminal
    os.execlp(cmd[0], *cmd)


@click.command("chat")
@click.argument("message", default="")
@click.option("--compress/--no-compress", default=True, show_default=True)
@click.option("--no-context", "skip_context", is_flag=True,
              help="Docs only, skip codebase files")
@click.option("--ext", "-e", multiple=True)
@click.option("--max-files", default=20, show_default=True)
@click.option("--model", "-m", default="")
@click.option("--continue", "cont", is_flag=True,
              help="Continue the most recent Claude conversation")
@click.option("--name", "-n", default="", help="Name this session")
def chat(message, compress, skip_context, ext, max_files, model, cont, name):
    """
    Open an interactive Claude session with forge context in the system prompt.

    Forge compiles your spec docs into the system prompt so Claude knows your
    project from the first message — no copy-pasting needed.

    \b
    Examples:
      forge chat                            open session with full context
      forge chat "let's build TASK-1"       open session with initial message
      forge chat --no-context               docs only, no codebase
      forge chat --continue                 resume last session
      forge chat --name "auth-sprint"       name this session
    """
    _check_claude()

    try:
        content = _compile(
            compress=compress,
            with_context=not skip_context,
            ext=tuple(ext),
            max_files=max_files,
        )
    except FileNotFoundError:
        console.print("[red]Run `forge init` first.[/red]")
        return

    from forge.core.compress import estimate_tokens

    cmd = ["claude"]

    if content:
        session_path = _write_session_file(content)
        tok = estimate_tokens(content)
        console.print(
            f"[green]forge[/green] → context loaded  "
            f"[dim]~{tok:,} tokens | compression {'on' if compress else 'off'}[/dim]"
        )
        cmd += ["--append-system-prompt-file", str(session_path)]
    else:
        console.print(
            "[yellow]No forge docs found.[/yellow] "
            "Run [bold]forge docs scaffold[/bold] to create them."
        )

    if model:
        cmd += ["--model", model]
    if cont:
        cmd += ["--continue"]
    if name:
        cmd += ["--name", name]
    if message:
        cmd.append(message)

    console.print()
    # Replace current process with claude — hands control to the CLI
    os.execlp(cmd[0], *cmd)
