"""
forge run — compile all spec docs + codebase context into one AI prompt.

This is the main "one-stop" command: reads persona, constitution, skills,
architecture, context, tasks, adds compressed codebase files, and outputs
a complete prompt ready to paste into Claude (or any AI).
"""

import os
from datetime import datetime, timezone
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.table import Table
from rich import box

console = Console()

_HEADER = """\
<!--
  Generated by forge · {timestamp}
  Tokens (est.): {tokens}
  Files in context: {file_count}
  Docs loaded: {doc_count}
-->

"""

_SECTION = """\
---

## {title}

{content}

"""

_FOOTER = """\
---

## Your Instruction

{instruction}
"""

_DEFAULT_INSTRUCTION = (
    "Implement the tasks listed above. "
    "Follow the rules and patterns defined in this session exactly. "
    "Return only the files you changed."
)


def _load_docs() -> list[tuple[str, str, str]]:
    """
    Returns list of (filename, section_title, content) in assembly order.
    Skips files that don't exist or are empty.
    """
    from forge.core.templates import ASSEMBLY_ORDER, SECTION_TITLES
    from forge.core.store import get_store

    docs_dir = get_store() / "docs"
    if not docs_dir.exists():
        return []

    result = []
    seen = set(ASSEMBLY_ORDER)

    # Ordered known files first
    for filename in ASSEMBLY_ORDER:
        path = docs_dir / filename
        if path.exists():
            content = path.read_text().strip()
            if content:
                title = SECTION_TITLES.get(filename, filename.replace(".md", "").title())
                result.append((filename, title, content))

    # Then any custom user files not in ASSEMBLY_ORDER
    for path in sorted(docs_dir.glob("*.md")):
        if path.name not in seen and path.exists():
            content = path.read_text().strip()
            if content:
                title = path.stem.replace("-", " ").replace("_", " ").title()
                result.append((path.name, title, content))

    return result


def _collect_context_files(
    root: str = ".",
    extensions: tuple[str, ...] = (),
    max_files: int = 30,
    max_file_bytes: int = 40_000,
) -> list[tuple[str, str]]:
    """Returns list of (path, content) for relevant source files."""
    from forge.commands.context import _collect_files, _SKIP_DIRS, _SKIP_EXTS

    files = _collect_files(root)
    if extensions:
        files = [f for f in files if os.path.splitext(f)[1].lower() in extensions]

    result = []
    for f in files[:max_files]:
        try:
            size = os.path.getsize(f)
            if size > max_file_bytes:
                result.append((f, f"[skipped — {size // 1024} KB]"))
                continue
            with open(f, "r", errors="replace") as fh:
                result.append((f, fh.read()))
        except (OSError, PermissionError):
            result.append((f, "[could not read]"))

    return result


@click.command("run")
@click.option("--task", "-t", default="",
              help="Append a specific instruction (overrides default)")
@click.option("--compress/--no-compress", default=True, show_default=True,
              help="Apply caveman compression to reduce tokens")
@click.option("--context/--no-context", "with_context", default=True, show_default=True,
              help="Include codebase files in the prompt")
@click.option("--ext", "-e", multiple=True,
              help="Only include these file extensions (e.g. -e .py -e .ts)")
@click.option("--max-files", default=20, show_default=True,
              help="Max source files to include in context")
@click.option("--copy/--no-copy", default=True, show_default=True,
              help="Copy result to clipboard")
@click.option("--output", "-o", default="",
              help="Also save to a file")
@click.option("--preview", "-p", is_flag=True,
              help="Show a summary table instead of the full prompt")
def run(task, compress, with_context, ext, max_files, copy, output, preview):
    """
    Compile all spec docs + codebase context into one AI prompt.

    \b
    Workflow:
      1.  forge docs scaffold        create the starter .md files
      2.  edit .forge/docs/*.md      fill in your project details
      3.  forge run --copy           generate prompt → clipboard
      4.  paste into Claude CLI      and describe what you want

    \b
    Examples:
      forge run
      forge run --task "Only implement TASK-1, skip the rest"
      forge run --no-context --copy
      forge run -e .py -e .ts --max-files 15 -o prompt.md
    """
    from forge.core.compress import compress as compress_fn, estimate_tokens, compression_ratio
    from forge.core.store import get_store

    # ── Load spec docs ────────────────────────────────────────────────────
    try:
        doc_sections = _load_docs()
    except FileNotFoundError:
        console.print("[red]No .forge directory found. Run `forge init` first.[/red]")
        return

    if not doc_sections:
        console.print(
            "[yellow]No spec docs found.[/yellow]\n"
            "Run [bold]forge docs scaffold[/bold] to create them, "
            "then edit and re-run."
        )
        return

    # ── Build file tree block ─────────────────────────────────────────────
    context_block = ""
    context_files: list[tuple[str, str]] = []
    if with_context:
        context_files = _collect_context_files(
            root=".",
            extensions=tuple(ext),
            max_files=max_files,
        )
        if context_files:
            tree_lines = []
            prev_dir = None
            for f, _ in context_files:
                d = os.path.dirname(f) or "."
                if d != prev_dir:
                    tree_lines.append(f"  {d}/")
                    prev_dir = d
                tree_lines.append(f"    {os.path.basename(f)}")

            file_blocks = []
            for f, content in context_files:
                if content.startswith("["):
                    file_blocks.append(f"**{f}**\n{content}")
                else:
                    c = compress_fn(content) if compress else content
                    file_blocks.append(f"**{f}**\n```\n{c}\n```")

            context_block = (
                "### File Tree\n```\n"
                + "\n".join(tree_lines)
                + "\n```\n\n"
                + "\n\n".join(file_blocks)
            )

    # ── Assemble prompt ───────────────────────────────────────────────────
    parts = []

    for filename, title, content in doc_sections:
        c = compress_fn(content) if compress else content
        parts.append(_SECTION.format(title=title, content=c))

    if context_block:
        parts.append(_SECTION.format(title="Codebase", content=context_block))

    instruction = task.strip() or _DEFAULT_INSTRUCTION
    parts.append(_FOOTER.format(instruction=instruction))

    body = "\n".join(parts)
    token_estimate = estimate_tokens(body)

    header = _HEADER.format(
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        tokens=f"~{token_estimate:,}",
        file_count=len(context_files),
        doc_count=len(doc_sections),
    )

    result = header + body

    # ── Preview mode ──────────────────────────────────────────────────────
    if preview:
        _show_preview(doc_sections, context_files, token_estimate, compress, instruction)
        return

    # ── Output ────────────────────────────────────────────────────────────
    _print_summary(doc_sections, context_files, token_estimate, compress)

    if output:
        Path(output).write_text(result)
        console.print(f"[green]✓[/green] Saved to [bold]{output}[/bold]")

    if copy:
        try:
            import pyperclip
            pyperclip.copy(result)
            console.print("[green]✓[/green] Copied to clipboard — paste into Claude.")
        except Exception:
            console.print("[yellow]pyperclip not available.[/yellow]")
            if not output:
                click.echo(result)
    else:
        click.echo(result)


def _print_summary(
    doc_sections: list,
    context_files: list,
    token_estimate: int,
    compressed: bool,
) -> None:
    text = Text()
    text.append("\n  Docs included:   ", style="bold")
    text.append(f"{len(doc_sections)}\n")
    for _, title, content in doc_sections:
        text.append(f"    ✓ {title}\n", style="green")

    text.append("\n  Codebase files:  ", style="bold")
    text.append(f"{len(context_files)}\n")

    text.append("\n  Compression:     ", style="bold")
    text.append("on\n" if compressed else "off\n")

    text.append("\n  Est. tokens:     ", style="bold")
    color = "green" if token_estimate < 8000 else "yellow" if token_estimate < 20000 else "red"
    text.append(f"~{token_estimate:,}\n", style=color)

    console.print(Panel(text, title="[bold]forge run[/bold]", border_style="cyan"))


def _show_preview(
    doc_sections: list,
    context_files: list,
    token_estimate: int,
    compressed: bool,
    instruction: str,
) -> None:
    from forge.core.compress import estimate_tokens

    table = Table(box=box.ROUNDED, show_header=True, header_style="bold")
    table.add_column("Section", min_width=20)
    table.add_column("Source", width=22)
    table.add_column("Est. tokens", width=12, justify="right")

    for filename, title, content in doc_sections:
        tok = estimate_tokens(content)
        table.add_row(title, filename, f"~{tok:,}")

    if context_files:
        total_ctx = sum(estimate_tokens(c) for _, c in context_files if not c.startswith("["))
        table.add_row(
            "Codebase",
            f"{len(context_files)} files",
            f"~{total_ctx:,}",
            style="dim",
        )

    table.add_row(
        "Instruction",
        "—",
        f"~{estimate_tokens(instruction):,}",
        style="dim",
    )

    console.print(table)
    color = "green" if token_estimate < 8000 else "yellow" if token_estimate < 20000 else "red"
    console.print(
        f"\n  Total est. tokens: [{color}]~{token_estimate:,}[/{color}]"
        f"  |  Compression: {'on' if compressed else 'off'}\n"
    )
    console.print("[dim]Run without --preview to generate and copy the full prompt.[/dim]")
